MAIN_URL_UCRAFT = "https://sso.stage.ucraft.ai"
KAFKA_CLIENT_ID = "erp-next-producer"
KAFKA_BOOTSTRAP_SERVERS = "kafka-broker-0-dev.stage.ucraft.ai:9094"
KAFKA_SASL_USERNAME = "admin"
KAFKA_SASL_PASSWORD = "yt3aSUX644UgCPpJzA3Q5AZ6jWZyZ9"
KAFKA_PARTITIONER = "murmur2"
KAFKA_SECURITY_PROTOCOL = "SASL_PLAINTEXT"
KAFKA_TOPIC = "erp-next-events"